config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [:new, :create]

  get 'store/index'

  namespace :admin do
    resources :categories, :products
    resources :orders, only: [:index, :edit, :destroy]
    root 'orders#index'
  end

  resources :categories

  root to: 'store#index', as: 'store'

  get 'search' => 'searches#index'

  resources :carts, only: [:update, :show, :destroy]
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products
  accepts_nested_attributes_for :order_products

  validates :name, :phone, :adress, presence: true

  enum status: [:active, :closed]

  def discount
    @discount ||= case sum.to_i
                  when 0..4999
                    0
                  when 5000..9999
                    sum * 0.05
                  when 10_000..14_999
                    sum * 0.1
                  else
                    sum * 0.15
                  end
  end

  def total
    sum - discount
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  before_action :set_order, only: [:edit, :destroy]

  layout 'admin'

  def index
    @orders = Order.order(status: :asc, created_at: :desc)
              .page(params[:page]).per(20)
  end

  def edit
    @order.closed!
    redirect_to admin_orders_path
  end

  def destroy
    @order.destroy
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def set_params
    params.require(:order).permit!
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  layout 'store'

  def new
    @products = Product.where(id: session[:cart])
    @order = Order.new(products: @products)
  end

  def create
    return if session[:cart].nil?
    @order = Order.create(order_params)
    if @order.save
      flash[:success] = t('order.created')
      session[:cart] = nil
      redirect_to store_path
      Notification.order_notification(@order.id).deliver_now
    else
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit!
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/destroy.js.erb
$("#order-id_<%= params[:id] %>").remove();

app/views/admin/orders/edit.html.slim
h1 Editing order

== render 'form'

= link_to 'Show', @order
'|
= link_to 'Back', admin_orders_path

app/views/admin/orders/index.html.slim
h1 =t('order.listing')

- unless @orders.blank?
  table class='table table-striped'
    tbody
      tr
        th class='col-md-1' #{ t('order.id') } / #{ t('date') }
        th class='col-md-3' = t('product.listing')
        th class='col-md-5' = t('buyer_details')
        th class='col-md-2' #{ t('order.sum') } / #{ t('discount.title') }
        th class='col-md-1' = t('order.status.title')
      - @orders.each do |order|
        tr class='order' id="order-id_#{ order.id }"
          td
            p = order.id
            p = order.created_at.strftime('%d.%m.%Y')
          td
            - order.order_products.each do |product|
              => image_tag(product.image_name_url(:small), alt: product.title)
              p #{ product.quantity } x #{link_to product.title, admin_product_path(product.product_id) } (#{ t('product.art') } : #{product.article})
          td
            p = order.name
            p = order.phone
            p = order.adress
            p = order.email
          td
            p #{ t('order.sum') }: #{number_to_currency(order.sum, locale: I18n.locale) }
          td
            p = t("order.status.#{ order.status }")
            - if !order.closed?
              p => link_to t('order.close'), edit_admin_order_path(order), class: 'btn btn-success'
            p => link_to t('destroy'), admin_order_path(order), data: { :confirm => t('confirm') }, method: :delete, remote: true, class: 'btn btn-danger'
- else
  h2 =t('order.no_new')

= paginate @orders