config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [:new, :create]

  get 'store/index'

  namespace :admin do
    resources :categories, :products
    resources :orders, only: [:index, :edit, :destroy]
    root 'orders#index'
  end

  resources :categories

  root to: 'store#index', as: 'store'

  get 'search' => 'searches#index'

  resources :carts, only: [:update, :show, :destroy]
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :title, presence: true
  validates :title, uniqueness: true

  has_many :products

  scope :top, lambda {
    joins('LEFT OUTER JOIN categories cts ON
      categories.id = cts.parent_id')
      .joins('INNER JOIN products ON products.category_id = cts.id
      OR products.category_id = categories.id')
      .group('categories.id')
  }
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  layout 'admin'

  def index
    @categories = Category.all.page(params[:page]).per(50)
  end

  def new
    @category = Category.new
    @categories = Category.all
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
    @categories = Category.all
  end

  def category_params
    params.require(:category).permit(:title, :parent_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout 'store'

  def index
  end

  def show
    @products = Product.for_category(params[:id]).page(params[:page]).per(20)
  end

  helper_method :for_category
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.slim
= simple_form_for [:admin, @category], html: { class: 'form-horizontal' } do |f|
  => f.input :title, label: t('name')
  => f.input :parent_id, collection: @categories, as: :select, label: t('category.parent'), prompt: t('category.choise')
  => f.submit t('save'), class: 'btn btn-success'
p
=> link_to t('back'), admin_categories_path, { class: 'btn btn-default' }

app/views/admin/categories/edit.html.slim
h1 =t('category.edit')

== render 'form', locals: { categories: @categories }

app/views/admin/categories/index.html.slim
h1 = t('category.listing')

= link_to t('category.new'), new_admin_category_path, class: 'btn btn-success'

- unless @categories.empty?
  table class='table table-striped'
    thead
      tr
        th class='col-md-8'
        th class='col-md-4'

    tbody
      - @categories.each do |category|
        tr
          td
            => link_to category.title, admin_category_path(category), class: 'btn btn-link'
          td
            => link_to t('edit'), edit_admin_category_path(category), class: 'btn btn-default'
            => link_to t('destroy'), admin_category_path(category), data: {:confirm => t('confirm') }, :method => :delete, class: 'btn btn-danger'
- else
  h2 =t('categories.no')

= paginate @categories

app/views/admin/categories/new.html.slim
h1 =t('category.new')

== render 'form', object: @categories

app/views/admin/categories/show.html.slim
p#notice = notice

p
  strong Title:
  = @category.title
p
  strong Parent:
  = @category.parent_id

= link_to t('edit'), edit_admin_category_path(@category)

= link_to t('back'), admin_categories_path