config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [:new, :create]

  get 'store/index'

  namespace :admin do
    resources :categories, :products
    resources :orders, only: [:index, :edit, :destroy]
    root 'orders#index'
  end

  resources :categories

  root to: 'store#index', as: 'store'

  get 'search' => 'searches#index'

  resources :carts, only: [:update, :show, :destroy]
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :title, :article, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :image_name, allow_blank: true, format: {
    with: /\.(jpg|png)/,
    message: ' must be .jpg or .png file'
  }

  belongs_to :category
  has_many :order_products
  mount_uploader :image_name, ProductUploader

  scope :for_category, lambda { |category|
    joins(:category)
      .where('products.category_id = ? or
         categories.parent_id = ?', category, category)
      .group('products.id')
  }

  scope :search, lambda { |search|
    joins(:category)
      .where('products.title ILIKE ? or
         categories.title ILIKE ?', "%#{search}%", "%#{search}%")
      .group('products.id')
  }
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  layout 'admin'

  def index
    @products = Product.all.page(params[:page]).per(50)
  end

  def show
  end

  def new
    @product = Product.new
    @categories = Category.all.map { |c| [c.title, c.id] }
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to [:admin, @product]
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to [:admin, @product]
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to admin_products_path
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit!
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_name, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.slim
= simple_form_for [:admin, @product], html: { class: 'form-horizontal' } do |f|
  => f.input :title, label: t('name')
  => f.input :article, label: t('product.article')
  => f.input :price, label: t('price'), placeholder: t('currency')
  => f.association :category, include_blank: false, label: t('category.title'), prompt: t('category.choise')
  => f.input :image_name, as: :file, label: t('image')
  p
  => f.submit t('save'), class: 'btn btn-success'
p
=> link_to t('back'), admin_products_path, class: 'btn btn-default'

app/views/admin/products/edit.html.slim
h1 =t('product.edit')

== render 'form', locals: { categories: @categories }

app/views/admin/products/index.html.slim
h1 =t('product.listing')

= link_to t('product.new'), new_admin_product_path, class: 'btn btn-success'

- unless @products.empty?
  table class='table table-striped'
    thead
      tr
        th
        th =t('name')
        th =t('category.title')
        th =t('product.article')
        th =t('price')
        th
    tbody
      - @products.each do |product|
        tr
          td = image_tag(product.image_name_url(:thumb), alt: product.title)
          td = link_to product.title, admin_product_path(product)
          td = product.category ? (link_to product.category.title, admin_category_path(product.category_id)) : ''
          td = product.article
          td = number_to_currency(product.price, locale: I18n.locale)
          td
            => link_to t('edit'), edit_admin_product_path(product), class: 'btn btn-default'
            => link_to t('destroy'), admin_product_path(product), data: {:confirm => t('confirm') }, :method => :delete, class: 'btn btn-danger'
- else
  h2 =t('product.no')

= paginate @products

app/views/admin/products/new.html.slim
h1 =t('product.new')

== render 'form', locals: { categories: @categories }

app/views/admin/products/show.html.slim
p#notice = notice

p
  = image_tag(@product.image_name_url(:large), alt: @product.title)
p
  strong =t('name')
p
  = @product.title
p
  strong =t('product.article')
p
  = @product.article
p
  strong =t('price')
p
  = sprintf("%0.02f руб", @product.price)

=> link_to t('edit'), edit_admin_product_path(@product), class: 'btn btn-default'

=> link_to t('back'), admin_products_path,{ class: 'btn btn-default' }