config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [:new, :create]

  get 'store/index'

  namespace :admin do
    resources :categories, :products
    resources :orders, only: [:index, :edit, :destroy]
    root 'orders#index'
  end

  resources :categories

  root to: 'store#index', as: 'store'

  get 'search' => 'searches#index'

  resources :carts, only: [:update, :show, :destroy]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def categories_group
    Category.top.group_by(&:parent_id)
  end

  def show_products_from_category_and_parents
    Product.products.group_by(&:category_id)
  end

  helper_method :categories_group, :show_products_from_category_and_parents
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(my_controller)
    :active if controller.controller_name.to_s == my_controller.to_s
  end

  def active_category(id)
    :active if params[:id].to_s == id.to_s
  end
end

app/views/application/_cart.html.slim
H2 = t('cart')

app/views/application/_cart_banner.html.slim
- if session[:cart].blank?
  = link_to store_path, class: 'btn btn-info' do
    => t('empty_cart')
    = image_tag('cart_empty.png')
- else
  = link_to new_order_path, class: 'btn btn-info'
    => t('in_cart', count: session[:cart].length)
    = image_tag('cart_full.png')

app/views/application/_category_listing.html.slim
h3 =t('category.listing')
ul class='nav nav-pills nav-stacked'
  - if top = categories_group[nil]
    - top.each do |c|
      li class="#{ active_category(c.id) }" role='presentation' = link_to c.title, category_path(c)
      ul class='nav nav-pills nav-stacked'
        - if categories_group[c.id].present?
          - categories_group[c.id].each do |category|
            li class='cat-children' role='presentation' class="#{ active_category(category.id) }" = link_to category.title, category_path(category)

app/views/application/_flash_messages.html.slim
- flash.each do |key, value|
  .alert class="alert-#{ key }"
    = value

app/views/application/_menu_top.html.slim
.navbar class='navbar-default navbar-fixed-top' role='navigation'
  .container
    .navbar-header id='logo'
      = link_to image_tag('logo.png'), store_path
    .collapse class='navbar-collapse'
      ul class='nav navbar-nav'
        li
          => link_to t('order.title_many'), admin_orders_path
        li class="#{ active_class(:products) }"
          => link_to t('product.title_many'), admin_products_path
        li class="#{ active_class(:categories) }"
          => link_to t('category.title_many'), admin_categories_path

app/views/application/_product.html.slim
.col-md-5 class='product'
  = link_to image_tag(product.image_name_url(:medium), alt: product.title), product.image_name_url(:large), rel: :lazybox
  .buy
    p class='product_title'
      = product.title
    .to_cart
      = button_to t('to_cart'), cart_path(product), method: :patch, remote: true, class: 'btn btn-success', id: "add_product_#{product.id}"
    .product_price
      = number_to_currency(product.price, locale: I18n.locale)

app/views/application/_search.html.slim
= simple_form_for '', url: search_path, method: 'get', html: { class: 'navbar-form navbar-left', role: 'search' } do |f|
  .form-group>
    = f.input :search, class: 'form-control', input_html: { value: params[:search], placeholder: t('text_for_search') }, required: false, label: false
  => f.submit t('search'), class: 'btn btn-success', name: nil

app/views/application/_top_info.html.slim
.top-info
  .row
    .col-md-5 class='info-group'
      .info-title
        p = t('we_are')
      .info
        p == t('address')
    .col-md-5 class='info-group'
      .info-title
        p = t('call')
      .info
        p 8 (968) 732 69 30
      .info-title
        p = t('working')
      .info
        p = t('working-time')

app/views/application/_user_menu_top.html.slim
.navbar class='navbar-default navbar-fixed-top' id='user_top_menu' role="navigation"
 .container
    .navbar-header id='logo'
      = link_to image_tag('logo.png'), store_path
    .collapse class='navbar-collapse'
      ul class='nav navbar-nav navbar-right'
        li id='cart-banner'
          = render 'cart_banner'
        li = render 'search'